<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class AboutController extends Controller
{
    /**
     * Generated by command > php artisan make:controller AboutController -i
     * ( -i => invoke)
     */
    public function __invoke(Request $request)
    {
        //
    }
}
